backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

#publish_mode: editorial_workflow #optional, enables publishing workflow

collections:
  - name: blog
    label: Blog
    folder: source/posts/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{title}}'
    fields:
      - {label: Titel, name: title, widget: string, required: true}
      - {label: Datum, name: date, widget: datetime}
      - {label: Omschrijving, name: description, widget: string}
      - {label: Afbeelding, name: image, widget: image}
      - {label: Tekst, name: body, widget: markdown}
